# Generated by Django 5.0.9 on 2024-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
